version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    expose:
      - "1433"
    ports:
      - "5050:1433"
    environment:
      - "MSSQL_SA_PASSWORD=Global5678"
      - "ACCEPT_EULA=Y"
      - "MSSQL_PID=Express"
    volumes:
      - /home/algos/sqlserver/database:/var/opt/mssql/data
    networks:
      - "APIServer"

networks:
  APIServer:
    name: APIServer
    external: true