version: '3'

services:
  app1:
    build:
      context: server1
    expose:
      - "5001"
    networks:
      - "APIServer"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  app2:
    build:
      context: server2
    expose:
      - "5002"
    networks:
      - "APIServer"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "80:80"
    networks:
      - "APIServer"

networks:
  APIServer:
    name: APIServer
    external: true